import '../modules/jquery/jquery.js'
import '@fortawesome/fontawesome-free/css/all.css'
import 'bootstrap'
import 'admin-lte/dist/js/adminlte.js'
import 'admin-lte/dist/css/adminlte.css'
import '../../styles/site.scss'
