name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore ../../Src/B2B.DataAccess/B2B.DataAccess.csproj
        dotnet restore ../../Src/B2B.DatabaseCreator/B2B.DatabaseCreator.csproj
        dotnet restore ../../Src/B2B.Logic/B2B.Logic.csproj
        dotnet restore ../../Src/B2B.Shared/B2B.Shared.csproj
        dotnet restore ../../Src/B2B.Web/B2B.Web.csproj
    - name: Build
      run: |
        dotnet build --no-restore ../../Src/B2B.DataAccess/B2B.DataAccess.csproj
        dotnet build --no-restore ../../Src/B2B.DatabaseCreator/B2B.DatabaseCreator.csproj
        dotnet build --no-restore ../../Src/B2B.Logic/B2B.Logic.csproj
        dotnet build --no-restore ../../Src/B2B.Shared/B2B.Shared.csproj
        dotnet build --no-restore ../../Src/B2B.Web/B2B.Web.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal
